Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define "ubuntu2204" do |machine|
        machine.vm.box = "mdziuban/cmag_ubuntu2204"
        machine.vm.box_version = "1.0.0"
        machine.vm.box_architecture = "amd64"
        machine.vm.synced_folder "workspace_ubuntu2204", "/home/vagrant/workspace"
    end

    config.vm.define "windows10" do |machine|
        machine.vm.box = "gusztavvargadr/visual-studio-2022-community-windows-11"
        machine.vm.box_version = "2022.2302.2401"
        machine.vm.box_architecture = "amd64"
        machine.vm.synced_folder "workspace_windows10", "/workspace"
        machine.vm.provision "shell", path: "guest_scripts/windows_provision.ps1"

        # Workaround for WinRM not working.
        machine.winrm.transport = :plaintext
        machine.winrm.basic_auth_only = true
    end

    config.vm.define "archlinux" do |machine|
        machine.vm.box = "generic/arch"
        machine.vm.box_architecture = "amd64"
        machine.vm.synced_folder "workspace_archlinux", "/home/vagrant/workspace"
        machine.vm.provision "shell", path: "guest_scripts/archlinux_provision.sh"
    end

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "8096"
        vb.cpus = "1" # For some reason Windows gets out of memory errors when compiling with multiple cores...
        vb.gui = true
    end
end
