name: Format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Format all files
      run: .github/scripts/format_linux.sh

    - name: Assert no diff
      run: git diff --exit-code
